version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/code/uploads
    environment:
      - SECRET_KEY=your_secret_key

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
